import Head from 'next/head'
import Image from 'next/image'
import dynamic from "next/dynamic";
const Test = dynamic(() => import("mfe1/Test"), {
  ssr: false,
});
// const test = await import('mfe1/Test');
// console.log(test);
// const Test = test.default;
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Test/>
    
    </>
  )
}
